### PR TITLE
Update MineReset.php

### PR DESCRIPTION
**Pull request by Pub4Game**
Added color and missing word

### CODE REVIEW

**Comment by Pub4Game** [comment]
Why do you constantly put "return true" if the action is actually and so interrupted?

**Comment by Falkirks** [comment]
@Pub4Game This is old logic that I haven't touched in ages, I am not entirely sure how or why it works. Therefore, I don't mess with it. I prefer to close my colours with a `TextFormat::RESET` for easier parsing. Also, the green colour on the success messages is rather annoying, there doesn't need to be a colour because the action was performed as expected.

**Comment by Pub4Game** [comment]
For example 

$sender->sendMessage(TextFormat::RED . "You do not have permission.");

$sender->sendMessage(TextFormat::RED . "You do not have permission." . TextFormat::RESET);

?

**Comment by Falkirks** [comment]
@Pub4Game That's what I mean, but I don't like the green messages, they are colour for the sake of colour.

**Comment by Pub4Game** [comment]
@Falkirks :) Well, I'll change color

**Pull request merged**
