### PR TITLE
Prevent /mine in the /help

### PR DESCRIPTION
**Pull request by Bamuel**
aka bad coding practices

### CODE REVIEW

**Comment by Falkirks** [comment]
I wasn't sure this was how permission nodes operated. Will granting a child node grant all parent nodes? For example, if I grant `minereset.command.create` will that grant `minereset`?

**Comment by ifvictr** [comment]
@Falkirks I don't think granting a child node will bubble up to its parent nodes. @Bamuel What do you mean by "prevent /mind in the /help" to be exact?

**Comment by ABAxStorm** [comment]
@Falkirks Not at all.

**Comment by Bamuel** [comment]
@ifvictr @Falkirks So ingame when you type /help you get a list of commands, and /mine is on it, when a non-op user tries /mine , it pops up "no perms" but doing what I did it removes /mine in the /help (unless the user is op).

**Comment by Falkirks** [comment]
@ABAxStorm Thanks. 

@Bamuel So my problem is that if I grant `minereset.command.create`, the command will not show up in the help menu because the user does not have `minereset`.

**Comment by ifvictr** [comment]
@Bamuel What do you mean by remove it? The description/command for /mine will be hidden from /help?

@Falkirks Shouldn't you guys use `minereset.command`?

**Comment by Falkirks** [comment]
@ifvictr Probably, but that would have the same issue.

**Comment by ifvictr** [comment]
@Falkirks The issue is what @Bamuel said, right? Don't all commands show in /help, despite the permissions the command sender has?

**Comment by Bamuel** [comment]
👍

**Comment by Falkirks** [comment]
@Bamuel I didn't merge it. I just rebased it so it is up to speed.

**Pull request closed without merging**
